name: gateway
namespace: default

replicaCount: 1

image:
  repository: ghcr.io/askaryankarine/bmstu-ds-4/gateway
  tag: "latest"

postgres:
  dsn: ""

app:
  port: 80
  env: "prod"

gateway:
  reservation: "http://reservation/api/v1"
  loyalty: "http://loyalty/default/api/v1"
  payment: "http://payment/default/api/v1"